# TODO: when the automatic build and push to provider tasks are working, this labeler action can be re-activated

# name: "Labeler"
# on:
#   pull_request:
#     types: [opened, synchronize, reopened]

# jobs:
#   label:
#     runs-on: ubuntu-latest
#     steps:
#       - name: "Label PR"
#         uses: actions/labeler@v3
#         with:
#           repo-token: "${{ secrets.GITHUB_TOKEN }}"